from SegmentTable import *

imgpath = 'copy/c1930/deskew2' #Image or directory of images to segment
outpath = 'copy/c1930/outjson2' #Path to output JSON results
outimg = 'copy/c1930/out3' #Path to output image of results (optional; for visual inspection)
#template = 'copy/c1930/template.json' #JSON file generated by another image of same collection
template = ''
filter = True #Filter output (disabling will greatly reduce precision but may help for classification)
exprows = 51 #Number of output rows

mainf(imgpath, outpath, outimg, template, filter, exprows)