from SegmentTable import *

imgpath = 'put/path/here' #Image or directory of images to segment
outpath = '' #Path to output JSON results
outimg = '' #Path to output image of results (optional; for visual inspection)
#template = 'copy/c1930/template.json' #JSON file generated by another image of same collection
template = ''
filter = True #Filter output (disabling will greatly reduce precision but may help for classification)
exprows = 100 #Number of output rows

mainf(imgpath, outpath, outimg, template, filter, exprows)